name: Label First Issue
on:
  pull_request:
    branches: [master]
  issues:
    types: [opened]
jobs:
  add-label:
    name: Add Label
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: ${{ steps.first_issue.outputs.labels }}
          issue-number: ${{ steps.first_issue.outputs.issue_number }}
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Add comment to first issue
        if: steps.first_issue.outputs.is_first_interaction == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Thank you for informing us!'
            })