name: Label Pull Request
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  label_pull_request:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changes in DeliveryServiceAppTest project
        id: delivery_changes
        run: |
          if git diff --name-only HEAD^..HEAD | grep -q "DeliveryServiceAppTest"; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Apply labels to pull request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request
            const changes = '${{ steps.delivery_changes.outputs.changes }}' == 'true'

            if (changes) {
              await github.issues.addLabels({
                issue_number: pr.number,
                labels: ['Test']
              })
            } else {
              const projectName = pr.head.repo.name.split('-').pop()

              if (/\bbug\b/i.test(pr.head_commit.message)) {
                await github.issues.addLabels({
                  issue_number: pr.number,
                  labels: [`Fixbug-${projectName}`]
                })
              } else {
                await github.issues.addLabels({
                  issue_number: pr.number,
                  labels: [`Feature-${projectName}`]
                })
              }
            }
