name: "Pull Request Labeler"
on:
  pull_request: [master]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: windows-latest
    steps:
    - uses: actions/labeler@v4