name: "Pull Request Labeler"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment_pull_req:
    permissions:
      contents: read
      pull-requests: write
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add label  
        uses: ./.github/workflows/labeler.yaml