name: Label Pull Request

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  label_pull_request:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changes in DeliveryServiceAppTest project
        id: delivery_changes
        run: |
          if git diff --name-only HEAD^..HEAD | grep -q "DeliveryServiceAppTest"; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Label pull request
        uses: marvinpinto/action-automatic-label@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/workflows/labeler.yml
